name: Deploy to Production

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init
        working-directory: ./prod

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./prod

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./prod
